{% set version = "5.0.0" %}

package:
  name: envisage
  version: {{ version }}

source:
  fn: envisage-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/e/envisage/envisage-{{ version }}.tar.gz
  md5: f9cc41cdc98f206b6e87863870c318f9

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - traits
    - apptools

test:
  imports:
    - envisage

about:
  home: http://docs.enthought.com/envisage/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: extensible application framework
  description: |
    Envisage is a Python-based framework for building extensible applications,
    that is, applications whose functionality can be extended by adding
    "plug-ins".
  doc_url: http://docs.enthought.com/envisage/index.html
  doc_source_url: https://github.com/enthought/envisage/blob/master/docs/source/index.rst
  dev_url: https://github.com/enthought/envisage

extra:
  recipe-maintainers:
    - grlee77
