travis:
  secure:
    BINSTAR_TOKEN: LosxQcFbOX4umDsU7A3TaOT+SjyctGB41R6HSAjNPnMGzV9WkprwMb8IgHEd36Clsq8MHWe1B1zNkJL44dT1ZyIo8WngzT1bwRUbPxPFVBl5sfrUCji4jrrWEPJh8NgYjTw0mJUNg1m90MWK4Rt0WS57xHMYYQ43XMneB8izxwsV0uamzolxzIBkbtMmkS3OClsfj9uU2xYQGciM1ugB8DZq/HJwnIYjv0xD+T5dq9EckAQHJ1iYHviOfTxRwqdONkEK7Ox+rIXesD7zXiurGZ8GRmkl5ha+iQVu0JSRQcNjWxcQNOCOb7yuXCRkzOBodUkSCRwZo5v6tuPyLg1NEnxldhJOqEC4jDtyABWquiIzfCbw77HZ5NraZ4vFE+MwD2w56ISqEMTl2BQvAyM2qt/WrQ9RowqpQ5PgtJfQ9INtQFCNAKg9X/2+bxFcArm3FU1j0HtjkXMCDtcHwTmOnL8uDP5Z99q07FzNvUfTXfQokufgSwhHz3JUfVFRgOo6aU81j6bRF62my3z1zFlTpQdQ5C0QPIXtbUHiVjpgVcKo5oFFN7E8C4Jnw7CSw3jIaur75UFxIu5Prb0sU6STo9J5nAg2XwKIGrOMKBF6CCDtySu98DB0kykR0DWYNpqIUnKgna+smbvfESWfrbO15xKXZZa/sgsHebeOmWDTOoI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
